-- 金融服务数据库表结构
-- V1: 创建应收款和贷款相关表

-- 应收款表
CREATE TABLE IF NOT EXISTS t_receivable (
    id BIGINT PRIMARY KEY COMMENT '应收款ID',
    receivable_no VARCHAR(50) NOT NULL COMMENT '应收款编号',
    business_scene INT COMMENT '业务场景: 1-入库生成, 2-转让配送签收生成',
    source_voucher_id BIGINT COMMENT '关联物流单ID',
    creditor_ent_id BIGINT COMMENT '债权人ID',
    debtor_ent_id BIGINT COMMENT '债务人ID',
    initial_amount DECIMAL(20,2) NOT NULL COMMENT '原始金额',
    adjusted_amount DECIMAL(20,2) NOT NULL COMMENT '结算金额',
    collected_amount DECIMAL(20,2) NOT NULL DEFAULT 0 COMMENT '已回收金额',
    balance_unpaid DECIMAL(20,2) NOT NULL COMMENT '待还余额',
    currency VARCHAR(10) DEFAULT 'CNY' COMMENT '币种',
    due_date DATETIME COMMENT '最后还款日',
    status INT NOT NULL DEFAULT 1 COMMENT '状态: 1-待确认, 2-生效中, 3-部分还款, 4-已结清, 5-逾期',
    is_financed INT DEFAULT 0 COMMENT '融资标识: 0-未融资, 1-已融资',
    parent_id BIGINT COMMENT '父级ID(拆分时指向原账单)',
    chain_tx_hash VARCHAR(100) COMMENT '区块链交易哈希',
    remark VARCHAR(255) COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_receivable_no (receivable_no),
    INDEX idx_source_voucher_id (source_voucher_id),
    INDEX idx_creditor_ent_id (creditor_ent_id),
    INDEX idx_debtor_ent_id (debtor_ent_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应收款表';

-- 还款记录表(应收款还款)
CREATE TABLE IF NOT EXISTS t_repayment_record (
    id BIGINT PRIMARY KEY COMMENT '还款记录ID',
    receivable_id BIGINT NOT NULL COMMENT '关联应收款ID',
    repayment_no VARCHAR(50) NOT NULL COMMENT '还款编号',
    repayment_type INT NOT NULL COMMENT '还款类型: 1-现金还款, 2-仓单抵债',
    amount DECIMAL(20,2) NOT NULL COMMENT '还款金额',
    currency VARCHAR(10) DEFAULT 'CNY' COMMENT '币种',
    payment_voucher VARCHAR(100) COMMENT '付款凭证',
    receipt_id BIGINT COMMENT '仓单ID(仓单抵债时)',
    offset_price DECIMAL(20,2) COMMENT '抵债价格',
    signature_hash VARCHAR(100) COMMENT '签名哈希',
    repayment_time DATETIME COMMENT '还款时间',
    chain_tx_hash VARCHAR(100) COMMENT '区块链交易哈希',
    remark VARCHAR(255) COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_repayment_no (repayment_no),
    INDEX idx_receivable_id (receivable_id),
    INDEX idx_repayment_type (repayment_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='还款记录表';

-- 质押贷款表
CREATE TABLE IF NOT EXISTS t_loan (
    id BIGINT PRIMARY KEY COMMENT '贷款ID',
    loan_no VARCHAR(50) NOT NULL COMMENT '贷款编号',
    borrower_ent_id BIGINT NOT NULL COMMENT '借款企业ID',
    borrower_ent_name VARCHAR(100) COMMENT '借款企业名称',
    finance_ent_id BIGINT COMMENT '金融机构ID',
    finance_ent_name VARCHAR(100) COMMENT '金融机构名称',
    receipt_id BIGINT NOT NULL COMMENT '质押仓单ID',
    receipt_no VARCHAR(50) COMMENT '仓单编号',
    goods_name VARCHAR(100) COMMENT '货物名称',
    warehouse_name VARCHAR(100) COMMENT '仓库名称',
    applied_amount DECIMAL(20,2) NOT NULL COMMENT '申请金额',
    approved_amount DECIMAL(20,2) COMMENT '审批金额',
    loan_amount DECIMAL(20,2) COMMENT '实际放款金额',
    applied_interest_rate DECIMAL(10,6) COMMENT '申请利率',
    approved_interest_rate DECIMAL(10,6) COMMENT '审批利率',
    loan_interest_rate DECIMAL(10,6) COMMENT '执行利率',
    loan_days INT COMMENT '贷款期限(天)',
    collateral_value DECIMAL(20,2) COMMENT '抵押物评估价值',
    pledge_rate DECIMAL(10,6) DEFAULT 0.7000 COMMENT '质押率',
    max_loan_amount DECIMAL(20,2) COMMENT '最大可贷金额',
    applied_time DATETIME COMMENT '申请时间',
    approved_time DATETIME COMMENT '审批时间',
    disbursed_time DATETIME COMMENT '放款时间',
    loan_start_date DATE COMMENT '贷款起息日',
    loan_end_date DATE COMMENT '贷款到期日',
    repaid_principal DECIMAL(20,2) DEFAULT 0 COMMENT '已还本金',
    repaid_interest DECIMAL(20,2) DEFAULT 0 COMMENT '已还利息',
    repaid_penalty DECIMAL(20,2) DEFAULT 0 COMMENT '已还罚息',
    outstanding_principal DECIMAL(20,2) COMMENT '剩余本金',
    outstanding_interest DECIMAL(20,2) COMMENT '应收利息',
    outstanding_penalty DECIMAL(20,2) DEFAULT 0 COMMENT '应收罚息',
    status INT NOT NULL DEFAULT 1 COMMENT '状态: 1-待审批, 2-已拒绝, 3-已取消, 4-待放款, 5-已放款, 6-还款中, 7-已结清, 8-逾期, 9-已违约',
    receivable_id BIGINT COMMENT '关联应收款ID',
    approve_remark VARCHAR(255) COMMENT '审批备注',
    reject_reason VARCHAR(255) COMMENT '拒绝原因',
    reject_time DATETIME COMMENT '拒绝时间',
    cancel_reason VARCHAR(255) COMMENT '取消原因',
    cancel_time DATETIME COMMENT '取消时间',
    chain_tx_hash VARCHAR(100) COMMENT '区块链交易哈希',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_loan_no (loan_no),
    INDEX idx_borrower_ent_id (borrower_ent_id),
    INDEX idx_finance_ent_id (finance_ent_id),
    INDEX idx_receipt_id (receipt_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='质押贷款表';

-- 贷款还款记录表
CREATE TABLE IF NOT EXISTS t_loan_repayment (
    id BIGINT PRIMARY KEY COMMENT '还款记录ID',
    loan_id BIGINT NOT NULL COMMENT '贷款ID',
    repayment_no VARCHAR(50) NOT NULL COMMENT '还款编号',
    principal_amount DECIMAL(20,2) NOT NULL COMMENT '本金金额',
    interest_amount DECIMAL(20,2) NOT NULL COMMENT '利息金额',
    penalty_amount DECIMAL(20,2) DEFAULT 0 COMMENT '罚息金额',
    total_amount DECIMAL(20,2) NOT NULL COMMENT '还款总金额',
    repayment_type VARCHAR(20) NOT NULL COMMENT '还款类型: CASH, RECEIPT_OFFSET, RECEIVABLE_OFFSET, COLLATERAL_DISPOSAL, PARTIAL',
    payment_voucher VARCHAR(100) COMMENT '付款凭证',
    payment_account VARCHAR(50) COMMENT '付款账户',
    offset_receipt_id BIGINT COMMENT '仓单抵债时使用的仓单ID',
    offset_receipt_no VARCHAR(50) COMMENT '仓单编号',
    offset_receivable_id BIGINT COMMENT '应收账款抵债时使用的应收款ID',
    offset_receivable_no VARCHAR(50) COMMENT '应收款编号',
    disposal_method VARCHAR(20) COMMENT '处置方式: AUCTION, DIRECT_SALE, WRITE_OFF',
    disposal_amount DECIMAL(20,2) COMMENT '处置金额',
    signature_hash VARCHAR(100) COMMENT '签名哈希',
    repayment_time DATETIME COMMENT '实际还款时间',
    status INT DEFAULT 1 COMMENT '状态: 1-待确认, 2-已确认, 3-已拒绝',
    chain_tx_hash VARCHAR(100) COMMENT '区块链交易哈希',
    remark VARCHAR(255) COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_repayment_no (repayment_no),
    INDEX idx_loan_id (loan_id),
    INDEX idx_repayment_type (repayment_type),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='贷款还款记录表';

-- 贷款分期计划表
CREATE TABLE IF NOT EXISTS t_loan_installment (
    id BIGINT PRIMARY KEY COMMENT '分期ID',
    loan_id BIGINT NOT NULL COMMENT '贷款ID',
    installment_no INT NOT NULL COMMENT '期号',
    due_date DATE NOT NULL COMMENT '到期日期',
    principal_amount DECIMAL(20,2) NOT NULL COMMENT '应还本金',
    interest_amount DECIMAL(20,2) NOT NULL COMMENT '应还利息',
    total_amount DECIMAL(20,2) NOT NULL COMMENT '应还总额',
    repaid_amount DECIMAL(20,2) DEFAULT 0 COMMENT '已还金额',
    status INT DEFAULT 1 COMMENT '状态: 1-待还, 2-已还, 3-逾期',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_loan_installment (loan_id, installment_no),
    INDEX idx_loan_id (loan_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='贷款分期计划表';
