[common]
    cryptoType = 0

[network]
    peers = [
        "172.26.0.20:20000",
        "172.26.0.21:20001",
        "172.26.0.22:20002",
        "172.26.0.23:20003"
    ]
    defaultGroup = "group0"

[cryptoMaterial]
    certPath = "conf"
    disableSsl = "true"
    useSMCrypto = "false"

[threadPool]
    maxBlockingQueueSize = 1000

[account]
    keyStoreDir = "account"
    accountAddress = "0x6976c14175ddfae575ffab3845d89e155e09569d"
    accountFileFormat = "pem"
